# Generated by Django 5.1.7 on 2025-03-07 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('shea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancedriver',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitaldb'),
        ),
        migrations.AlterField(
            model_name='ambulancedriver',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
