# Generated by Django 5.1.7 on 2025-03-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shea', '0002_alter_ambulancedriver_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancedriver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
