# Generated by Django 5.1.7 on 2025-03-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_doctorschedule_doctor_delete_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(max_length=100),
        ),
    ]
